---
 - name: Install MYSQl and Airflow in ubuntu
   hosts: localhost
   connection: local
   become: yes
   tasks:
           - name: install python mysql bindings
             apt: name=python-mysqldb state=installed
             become: yes
             become_method: sudo
           - name: install werkzeug
             pip: name=werkzeug state=installed version=0.16.0   
 
   roles: 
       - role: gnishanth4.mysql
         become: yes 
       - role: gnishanth4.airflow_role 
          
