---
 - name: Install MYSQl and Airflow in ubuntu
   hosts: localhost
   connection: local
   become: yes
   environment: 
     AIRFLOW_HOME: /etc/airflow

   roles:
        - role: pre-packages
        
        - role: mysql

        - role: airflow  
        
        - role: airflow-post-configs
        
        - role: airflow-logo-change

 

