---
 - name: Install MYSQl and Airflow in ubuntu
   hosts: localhost
   connection: local
   become: yes
   tasks:          
           - name: install python mysql bindings
             apt: name=python-mysqldb state=latest
             become: yes
             become_method: sudo
   roles:
        - role: mysql

        - role: airflow  

 

