#Install a role from git hub
 - name: pre-packages
   src: https://github.com/gnishanth4/airflow-pre-packages.git
   version: origin/master
 - name: mysql
   src: https://github.com/gnishanth4/ansible-role-mysql.git
   version: origin/master
 - name: airflow
   src: https://github.com/gnishanth4/airflow-role.git
   version: origin/master 
 - name: airflow-post-configs
   src: https://github.com/gnishanth4/airflow-post-configs.git
   version: origin/master
 - name: airflow-logo-change
   src: https://github.com/gnishanth4/airflow-brand-logo-change.git
   version: origin/master
